- hosts: localhost
  roles:
  - role: openmicroscopy.omero-server
  vars:
    ice_version: "3.6"
    ice_install_devel: False
    ice_python_wheel: https://github.com/ome/zeroc-ice-py-centos7/releases/download/0.1.0/zeroc_ice-3.6.4-cp27-cp27mu-linux_x86_64.whl
    omero_server_database_manage: False
    omero_server_systemd_setup: False
    omero_server_system_uid: 1000
